### ISSUE TITLE
Rename testing components to "component_name-current_month"

### ISSUE THREAD

**Issue by fuhuifang** [Azure/shrike#58]
Unit tests are taking too long, especially on a local machine. One possible cause is that we have too many versions. To mitigate this, suggest renaming the component every month, so it will get cleared up.

**Comment by dkmiller** [comment]
My guess is that we are also running a number of end-to-end tests that really don't need to "hit" a real AML workspace.

Suggest two mitigations (can + should do both):

1. Instead of worrying about reducing the number of versions _in_ the tests, we'll be provisioning a standalone workspace just for testing. That workspace can (and should) be deleted + re-provisioned on a bi-weekly basis. This will both help keep the workspace lightweight, but will also ensure that no private / sensitive data sticks around.
2. Clearly distinguish between unit and e2e tests (former is < 1s, runs entirely using local compute, latter takes longer, talks to the outside world). We should have lots of the former, as few as possible as the latter. I see a bit of "creep" in that a lot of tests are being bundled into copy/pasted e2e tests, where they should be clean, simple, unit tests. @haozhestat , let's talk more about this.

**Comment by fuhuifang** [comment]
@dkmiller has already created:
1. An AML workspace just for testing - Microsoft Azure Machine Learning.
2. A secret (AZURE_CREDENTIALS) in the "shrike" repo encoding a service identity with contributor access to that workspace. You should be able to use this GitHub action to auth - Azure Login · Actions · GitHub Marketplace.

Will address unit vs. e2e tests in #19.
