### ISSUE TITLE
Smart mode not propagating into nested subfolders

### ISSUE THREAD

**Issue by dkmiller** [Azure/shrike#69]
(All Azure DevOps links here are internal.)

Basic summary is we modify a file two levels down from our import in additional includes, and the smart build does not consider that a change.

## Example

File modified: `pvt/utils/metric_logging.py`
File: "additional included": ../../pvt

PR: [Pull request 22229: metric logging update](https://eemo.visualstudio.com/TEE/_git/TEEGit/pullrequest/22229?_a=files&path=%2FOffline%2FPersonalizedViewTime%2Fpvt%2Futils%2Fmetric_logging.py)

Build (Step prepare components shows no active components): [Pipelines - Run 20210601.5 logs](https://eemo.visualstudio.com/TEE/_build/results?buildId=830812&view=logs&j=e24aea9e-642d-565f-0ea4-ee7a5a3b8fdc&t=5f7e3870-71f5-5ccb-156e-26d7a9a1cfab)

Build Config: [sign-register-build.yaml](https://eemo.visualstudio.com/TEE/_git/TEEGit?version=GBcompliant%2FPersonalizedViewTime&path=%2FOffline%2FPersonalizedViewTime%2Fsign-register-build.yaml)

Folder Structure: [pvt](https://eemo.visualstudio.com/TEE/_git/TEEGit?version=GBcompliant%2FPersonalizedViewTime&path=%2FOffline%2FPersonalizedViewTime%2Fpvt)

Example additional includes has pvt folder in utils: [module_spec.additional_includes](https://eemo.visualstudio.com/TEE/_git/TEEGit?version=GBcompliant%2FPersonalizedViewTime&path=%2FOffline%2FPersonalizedViewTime%2Fsteps%2FClassificationModel%2Fmodule_spec.additional_includes)

**Comment by fuhuifang** [comment]
I can't reproduce this locally, so I need to add some logs to debug. Is there a way to do this other than releasing a new version?

**Comment by haozhestat** [comment]
@fuhuifang and @dkmiller : I carefully examined the source code of [smart mode](https://github.com/Azure/shrike/blob/87548b342b09538b2e89be015ef2dc35e9cbb51d/shrike/build/commands/prepare.py#L513) this afternoon. I found a bug there. It only scan through the additional included directories and their first-layer subfolder. All other nested sub-subfolders are ignored by the current logic of "smart mode".

cc @thomasp-ms: Please correct me if my finding is wrong.

**Comment by haozhestat** [comment]
> I can't reproduce this locally, so I need to add some logs to debug. Is there a way to do this other than releasing a new version?

@fuhuifang : I don't think we need to release a new version for debugging. We could pip install locally in the **editable** mode then import some specific functions for testing rather than importing the whole class.

**Comment by fuhuifang** [comment]
> @fuhuifang and @dkmiller : I carefully examined the source code of [smart mode](https://github.com/Azure/shrike/blob/87548b342b09538b2e89be015ef2dc35e9cbb51d/shrike/build/commands/prepare.py#L513) this afternoon. I found a bug there. It only scans through the additional included directories and their first-layer subfolders. All other nested sub-subfolders are ignored by the current logic of "smart mode".
> 
> For instance, the modifed file `pvt/utils/metric_logging.py` is the **sub-sub-folder" of the additionally included directory `../../pvt`. The current logic of "smart mode" will ignore this modified file.
> 
> The proposed solution is to modify the function `is_in_subfolder(...)` to allow all nested folders.
> 
> cc @thomasp-ms: Please correct me if my finding is wrong.

`is_in_subfolder()` is searching for all the parents for `modified_file` and comparing with `../../pvt`, so I think the existing logic is correct. 

https://github.com/Azure/shrike/blob/6663a6fa4e18b42135477ef8bd1df32e24a67592/shrike/build/commands/prepare.py#L522

**Comment by fuhuifang** [comment]
> > I can't reproduce this locally, so I need to add some logs to debug. Is there a way to do this other than releasing a new version?
> 
> @fuhuifang : I don't think we need to release a new version for debugging. We could pip install locally in the **editable** mode then import some specific functions for testing rather than importing the whole class.

Sure, but is there a way to trigger an Azure DevOps pipeline using a "local" version? I can't repro the issue on my laptop.

**Comment by haozhestat** [comment]
> > @fuhuifang and @dkmiller : I carefully examined the source code of [smart mode](https://github.com/Azure/shrike/blob/87548b342b09538b2e89be015ef2dc35e9cbb51d/shrike/build/commands/prepare.py#L513) this afternoon. I found a bug there. It only scans through the additional included directories and their first-layer subfolders. All other nested sub-subfolders are ignored by the current logic of "smart mode".
> > For instance, the modifed file `pvt/utils/metric_logging.py` is the **sub-sub-folder" of the additionally included directory `../../pvt`. The current logic of "smart mode" will ignore this modified file.
> > The proposed solution is to modify the function `is_in_subfolder(...)` to allow all nested folders.
> > cc @thomasp-ms: Please correct me if my finding is wrong.
> 
> `is_in_subfolder()` is searching for all the parents for `modified_file` and comparing with `../../pvt`, so I think the existing logic is correct.
> 
> https://github.com/Azure/shrike/blob/6663a6fa4e18b42135477ef8bd1df32e24a67592/shrike/build/commands/prepare.py#L522

Nice catch! My bad.

**Comment by haozhestat** [comment]
@fuhuifang and @dkmiller : I created a branch `haoz/test-smart` in the PersonalViewTime repo. I copied the source code of shrike library into `haoz/test-smart` then pip install from local. I ran several ADO [pipelines](https://eemo.visualstudio.com/TEE/_build?definitionId=518&_a=summary) tonight, trying to figure out the root cause.

After commenting the following task in the build yaml file, the `smart mode` resumes working. Please check out this successful [pipeline](https://eemo.visualstudio.com/TEE/_build/results?buildId=831835&view=logs&j=e24aea9e-642d-565f-0ea4-ee7a5a3b8fdc&t=41bb769a-438e-531b-09e2-06f4c6c6f5ad&l=144). But I haven't figured out why.
```
#Copy everything in the steps folder as a dependency
- task: PowerShell@2
  displayName: 'Copy Additional Dependencies'
  inputs:
    targetType: filePath
    filePath: ./Offline/Shared/BuildScripts/CopyAdditionalModuleDependencies.ps1
    arguments: '-ModuleParentDirectoryPath $(Build.SourcesDirectory)/Offline/PersonalizedViewTime/steps'
```

**Comment by haozhestat** [comment]
I suspected that the root cause might be a "redundant" Task called "Copy Additional Dependencies" in the build.
```pwsh
 - task: PowerShell@2
    displayName: 'Copy Additional Dependencies'
    inputs:
      targetType: filePath
      filePath: ./Offline/Shared/BuildScripts/CopyAdditionalModuleDependencies.ps1
      arguments: '-ModuleParentDirectoryPath $(Build.SourcesDirectory)/Offline/PersonalizedViewTime/steps'
```

To verify that my finding is valid, I conducted a pseudo experiment this afternoon.

Step 1: I created two branches (i.e., haoz/test-smart-1, haoz/test-smart-2) from your main branch "compliant/PersonalViewTime":

- In the haoz/test-smart-1 branch, I added a dummy change to /Offline/PersonalizedViewTime/pvt/utils/metric_logging.py, and set activation_method: smart in the build config file.
- In the haoz/test-smart-2 branch, I added a dummy change to /Offline/PersonalizedViewTime/pvt/utils/metric_logging.py, set activation_method: smart in the build config file, and deleted the 'Copy Additional Dependencies' Task from the build yaml file.

Step2: I ran your signing & registering build under the above two branches:

- Run 20210603.6 is the build run under the haoz/test-smart-1 branch
- Run 20210603.8 is the build run under the haoz/test-smart-2 branch

Step3: Examined their logs at the `prepare components` step:

- Run 20210603.6 logs show that the smart mode failed to detect the modified file /Offline/PersonalizedViewTime/pvt/utils/metric_logging.py
- Run 20210603.8 logs show that the smart mode successfully detected the modified file /Offline/PersonalizedViewTime/pvt/utils/metric_logging.py

This experiment confirms that the failure of smart mode should be due to the "Copy Additional Dependencies" task.
