### ISSUE TITLE
Support "path_on_datastore" as a config parameter in the shrike.pipeline.AMLPipelineHelper

### ISSUE THREAD

**Issue by haozhestat** [Azure/shrike#96]

**Comment by fuhuifang** [comment]
@haozhestat  could you provide more context? Currently, users can specify it as in 
https://github.com/Azure/shrike/blob/308c2566753470239136c54406969f4762fa2537/tests/tests_pipeline/sample/pipeline/convert_tsv_to_ss_test.py#L112

**Comment by haozhestat** [comment]
@fuhuifang : Sorry for the lack of context when I created this issue.

This is a feature request from Ali Mahmoudzadeh originally. He was aware that `path_to_datastore` could be configured by using the component SDK API, but he suggested that `path_to_datatstore` should be supported in the `apply_recommened_settings()` like other parameters such as `input_mode` and `output_mode`.

This issue is of **low** priority. No blockers.

**Comment by fuhuifang** [comment]
My concern is adding it to `apply_recommend_settings()` will make the syntax more complicated (or at least it won't simplify things much), as this config is a per output thing. The current way of specifying it through component sdk api looks good to me, and I don't think `apply_recommened_settings()` support is very helpful.

Otherwise, if a user wants to use a generic path for all outputs (e.g. `some/prefix/{output-name}`), then `apply_recommened_settings()` support makes sense.

Happy to discuss more.

**Comment by haozhestat** [comment]
I agree with you, @fuhuifang . "path_on_datastore" is very specific to the component. 

Let's close this issue. Feel free to re-open it if there are any other customers requesting this feature.
